package handlers

import (
	"encoding/json"
	"fmt"
	"math"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"go_server/database"
	"go_server/models"

	"github.com/gin-gonic/gin"
)

type analysisRuleSnapshotResponse struct {
	Version     int                          `json:"version"`
	UpdatedAt   string                       `json:"updatedAt"`
	SourceRange analysisRuleSnapshotRange    `json:"sourceRange"`
	Total       int                          `json:"total"`
	CommonRows  []analysisRuleSnapshotCommon `json:"commonRows"`
	Notes       string                       `json:"notes,omitempty"`
	Path        string                       `json:"path,omitempty"`
}

type analysisRuleSnapshotRange struct {
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
}

type analysisRuleSnapshotCommon struct {
	Label  string                     `json:"label"`
	Sample int                        `json:"sample"`
	Rules  []analysisRuleSnapshotRule `json:"rules"`
}

type analysisRuleSnapshotRule struct {
	Value       string  `json:"value"`
	Sample      int     `json:"sample"`
	BothCorrect int     `json:"bothCorrect"`
	Rate        float64 `json:"rate"`
}

type analysisRuleSnapshotMatch struct {
	Item      analysisMatchResponse
	Bookmaker analysisRulePrediction
	Platform  analysisRulePrediction
}

type analysisRulePrediction struct {
	Outcome string
	Goal    string
	Score   string
	Total   int
}

// GenerateAnalysisRuleSnapshot rebuilds and writes the portable historical rule snapshot file.
func GenerateAnalysisRuleSnapshot(c *gin.Context) {
	startDate := strings.TrimSpace(c.DefaultQuery("start_date", "2026-05-28"))
	endDate := strings.TrimSpace(c.DefaultQuery("end_date", time.Now().Format("2006-01-02")))
	if _, err := time.Parse("2006-01-02", startDate); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid start_date, expected YYYY-MM-DD"})
		return
	}
	if _, err := time.Parse("2006-01-02", endDate); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid end_date, expected YYYY-MM-DD"})
		return
	}

	snapshot, err := buildAnalysisRuleSnapshot(startDate, endDate)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	path, err := writeAnalysisRuleSnapshot(snapshot)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	snapshot.Path = path
	c.JSON(http.StatusOK, snapshot)
}

func buildAnalysisRuleSnapshot(startDate string, endDate string) (analysisRuleSnapshotResponse, error) {
	var matches []models.Money
	query := database.DB.Where("date BETWEEN ? AND ? AND jingcai_id IS NOT NULL AND TRIM(jingcai_id) <> ?", startDate, endDate, "")
	query = query.Where("display_state IS NULL OR display_state <> ?", detailOnlyDisplayState)
	if err := query.Order("match_time ASC").Find(&matches).Error; err != nil {
		return analysisRuleSnapshotResponse{}, err
	}

	items := make([]analysisRuleSnapshotMatch, 0, len(matches))
	for _, match := range matches {
		if !analysisRuleSettled(match) {
			continue
		}
		item := buildAnalysisWithWeights(match, false)
		bookmaker := analysisRuleBookmakerPrediction(item)
		platform := analysisRulePlatformPrediction(item)
		items = append(items, analysisRuleSnapshotMatch{Item: item, Bookmaker: bookmaker, Platform: platform})
	}

	return analysisRuleSnapshotResponse{
		Version:   1,
		UpdatedAt: time.Now().Format(time.RFC3339),
		SourceRange: analysisRuleSnapshotRange{
			StartDate: startDate,
			EndDate:   endDate,
		},
		Total: len(items),
		CommonRows: []analysisRuleSnapshotCommon{
			buildAnalysisRuleCommonRow("胜平负双中", items, analysisRuleOutcomeBothCorrect, analysisRuleResultElements),
			buildAnalysisRuleCommonRow("大小球双中", items, analysisRuleGoalBothCorrect, analysisRuleGoalElements),
			buildAnalysisRuleCommonRow("比分命中", items, analysisRuleScoreHitCorrect, analysisRuleScoreElements),
		},
		Notes: "Generated by go_server from settled matches. This file is portable and should be committed with code.",
	}, nil
}

func writeAnalysisRuleSnapshot(snapshot analysisRuleSnapshotResponse) (string, error) {
	path := analysisRuleSnapshotWritePath()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return "", err
	}
	content, err := json.MarshalIndent(snapshot, "", "  ")
	if err != nil {
		return "", err
	}
	content = append(content, '\n')
	if err := os.WriteFile(path, content, 0644); err != nil {
		return "", err
	}
	absolutePath, err := filepath.Abs(path)
	if err != nil {
		return path, nil
	}
	return absolutePath, nil
}

func analysisRuleSnapshotWritePath() string {
	for _, path := range analysisRuleSnapshotCandidates() {
		if _, err := os.Stat(path); err == nil {
			return path
		}
		if _, err := os.Stat(filepath.Dir(path)); err == nil {
			return path
		}
	}
	return filepath.Join("data", "analysis_rule_snapshot.json")
}

func buildAnalysisRuleCommonRow(
	label string,
	items []analysisRuleSnapshotMatch,
	predicate func(analysisRuleSnapshotMatch) bool,
	extractor func(analysisRuleSnapshotMatch) []string,
) analysisRuleSnapshotCommon {
	rules := map[string]*analysisRuleSnapshotRule{}
	bothSample := 0
	for _, item := range items {
		bothCorrect := predicate(item)
		if bothCorrect {
			bothSample++
		}
		for _, value := range uniqueAnalysisRuleStrings(extractor(item)) {
			current := rules[value]
			if current == nil {
				current = &analysisRuleSnapshotRule{Value: value}
				rules[value] = current
			}
			current.Sample++
			if bothCorrect {
				current.BothCorrect++
			}
			if current.Sample > 0 {
				current.Rate = round4(float64(current.BothCorrect) / float64(current.Sample))
			}
		}
	}

	isScoreRow := strings.Contains(label, "比分")
	minSample := maxInt(2, int(math.Ceil(float64(len(items))*0.08)))
	minRate := 0.45
	if isScoreRow {
		minSample = maxInt(4, int(math.Ceil(float64(len(items))*0.04)))
		minRate = 0.28
	}
	out := make([]analysisRuleSnapshotRule, 0, len(rules))
	for _, rule := range rules {
		if rule.Sample >= minSample && rule.BothCorrect > 0 && rule.Rate >= minRate {
			out = append(out, *rule)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Rate != out[j].Rate {
			return out[i].Rate > out[j].Rate
		}
		if out[i].BothCorrect != out[j].BothCorrect {
			return out[i].BothCorrect > out[j].BothCorrect
		}
		if out[i].Sample != out[j].Sample {
			return out[i].Sample > out[j].Sample
		}
		return out[i].Value < out[j].Value
	})
	if len(out) > 8 {
		out = out[:8]
	}
	return analysisRuleSnapshotCommon{Label: label, Sample: bothSample, Rules: out}
}

func uniqueAnalysisRuleStrings(values []string) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" || value == "-" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	return out
}

func analysisRuleSettled(match models.Money) bool {
	return strings.Contains(match.DisplayState, "完") || match.Status >= 4
}

func analysisRuleActualOutcome(item analysisMatchResponse) string {
	if item.HomeScore > item.GuestScore {
		return "home"
	}
	if item.HomeScore < item.GuestScore {
		return "away"
	}
	return "draw"
}

func analysisRuleOutcomeBothCorrect(item analysisRuleSnapshotMatch) bool {
	actual := analysisRuleActualOutcome(item.Item)
	return item.Bookmaker.Outcome == actual && item.Platform.Outcome == actual
}

func analysisRuleGoalBothCorrect(item analysisRuleSnapshotMatch) bool {
	total := item.Item.HomeScore + item.Item.GuestScore
	return analysisRuleGoalCorrect(item.Bookmaker, total) && analysisRuleGoalCorrect(item.Platform, total)
}

func analysisRuleScoreHitCorrect(item analysisRuleSnapshotMatch) bool {
	actual := fmt.Sprintf("%d:%d", item.Item.HomeScore, item.Item.GuestScore)
	return item.Bookmaker.Score == actual || item.Platform.Score == actual
}

func analysisRuleGoalCorrect(prediction analysisRulePrediction, total int) bool {
	if prediction.Goal == "大球" {
		return total >= prediction.Total
	}
	if prediction.Goal == "小球" {
		return total <= prediction.Total
	}
	return total == prediction.Total
}

func analysisRuleBookmakerPrediction(item analysisMatchResponse) analysisRulePrediction {
	outcome := analysisRuleBookmakerOutcome(item)
	total := analysisRuleBookmakerTotal(item)
	goal := analysisRuleGoalDirection(total, item.QiushuPankou2)
	return analysisRulePrediction{Outcome: outcome, Goal: goal, Total: total, Score: analysisRuleScore(outcome, total, item.YapanPankou2)}
}

func analysisRulePlatformPrediction(item analysisMatchResponse) analysisRulePrediction {
	outcome := analysisRuleTextOutcome(item.Prediction)
	if outcome == "" {
		outcome = analysisRuleBookmakerOutcome(item)
	}
	if analysisRuleDrawRiskScore(item, analysisRuleBookmakerOutcome(item), outcome) >= 5 {
		outcome = "draw"
	}
	total := analysisRulePlatformTotal(item)
	goal := analysisRuleGoalDirection(total, item.QiushuPankou2)
	if strings.Contains(item.QiuPrediction, "大") {
		goal = "大球"
	} else if strings.Contains(item.QiuPrediction, "小") || strings.Contains(item.QiuPrediction, "闹0") {
		goal = "小球"
	}
	return analysisRulePrediction{Outcome: outcome, Goal: goal, Total: total, Score: analysisRuleScore(outcome, total, item.YapanPankou2)}
}

func analysisRuleBookmakerOutcome(item analysisMatchResponse) string {
	values := []float64{item.WinProbability, item.DrawProbability, item.LoseProbability}
	index := 0
	for i := 1; i < len(values); i++ {
		if values[i] > values[index] {
			index = i
		}
	}
	return []string{"home", "draw", "away"}[index]
}

func analysisRuleBookmakerTotal(item analysisMatchResponse) int {
	line := item.QiushuPankou2
	if line == 0 {
		line = item.QiushuPankou1
	}
	delta := item.QiushuPankou2 - item.QiushuPankou1
	if delta >= 0.25 {
		return maxInt(3, int(math.Floor(line+1.5)))
	}
	if delta <= -0.25 {
		return maxInt(0, int(math.Ceil(line)-1))
	}
	if line >= 2.75 {
		return 3
	}
	if line <= 2.25 {
		return 2
	}
	return 2
}

func analysisRulePlatformTotal(item analysisMatchResponse) int {
	line := item.QiushuPankou2
	if line == 0 {
		line = item.QiushuPankou1
	}
	if strings.Contains(item.QiuPrediction, "大") {
		return maxInt(3, int(math.Ceil(line)))
	}
	if strings.Contains(item.QiuPrediction, "小") || strings.Contains(item.QiuPrediction, "闹0") {
		return maxInt(0, int(math.Floor(line)))
	}
	return maxInt(0, int(math.Round(line)))
}

func analysisRuleGoalDirection(total int, line float64) string {
	if line > 0 {
		if float64(total) > line {
			return "大球"
		}
		if float64(total) < line {
			return "小球"
		}
	}
	return "盘口球"
}

func analysisRuleScore(outcome string, total int, handicap float64) string {
	if total <= 0 {
		return "0:0"
	}
	if outcome == "draw" {
		side := maxInt(0, int(math.Floor(float64(total)/2)))
		return fmt.Sprintf("%d:%d", side, side)
	}
	favorite := outcome
	if handicap > 0 {
		favorite = "home"
	} else if handicap < 0 {
		favorite = "away"
	}
	favoriteGoals := maxInt(1, int(math.Ceil(float64(total+1)/2)))
	underdogGoals := maxInt(0, total-favoriteGoals)
	homeGoals, awayGoals := underdogGoals, favoriteGoals
	if favorite == "home" {
		homeGoals, awayGoals = favoriteGoals, underdogGoals
	}
	if outcome == "home" && homeGoals <= awayGoals {
		homeGoals, awayGoals = favoriteGoals, underdogGoals
	}
	if outcome == "away" && awayGoals <= homeGoals {
		homeGoals, awayGoals = underdogGoals, favoriteGoals
	}
	return fmt.Sprintf("%d:%d", homeGoals, awayGoals)
}

func analysisRuleTextOutcome(value string) string {
	if strings.Contains(value, "平") {
		return "draw"
	}
	if strings.Contains(value, "客胜") || strings.Contains(value, "主负") || strings.Contains(value, "负") {
		return "away"
	}
	if strings.Contains(value, "主胜") || strings.Contains(value, "胜") {
		return "home"
	}
	return ""
}

func analysisRuleResultElements(item analysisRuleSnapshotMatch) []string {
	professional := analysisRuleProfessionalConsensus(item.Item)
	drawRisk := analysisRuleDrawRiskScore(item.Item, item.Bookmaker.Outcome, item.Platform.Outcome)
	return []string{
		"庄家" + analysisRuleOutcomeLabel(item.Bookmaker.Outcome),
		"平台" + analysisRuleOutcomeLabel(item.Platform.Outcome),
		analysisRuleAlignedLabel("庄平同向", "庄平分歧", item.Bookmaker.Outcome, item.Platform.Outcome, analysisRuleOutcomeLabel),
		analysisRuleOptionalLabel("凯体同向", professional, analysisRuleOutcomeLabel),
		"凯利" + analysisRuleJoin(item.Item.KaiLiResult),
		"体彩" + analysisRuleJoin(item.Item.TiCaiResult),
		"亚盘" + analysisRuleHandicapBucket(item.Item.YapanPankou2),
		"让球热度" + analysisRuleHeatBucket(item.Item.YaPanTouZhu, "主热", "客热"),
		analysisRuleDrawRiskLabel(drawRisk, 4, "平局风险高"),
		analysisRuleDrawRiskLabel(drawRisk, 5, "平局风险强"),
	}
}

func analysisRuleGoalElements(item analysisRuleSnapshotMatch) []string {
	return []string{
		"庄家" + item.Bookmaker.Goal,
		"平台" + item.Platform.Goal,
		analysisRuleAlignedLabel("庄平同向", "庄平球数分歧", item.Bookmaker.Goal, item.Platform.Goal, func(value string) string { return value }),
		"盘口" + analysisRuleGoalLineBucket(item.Item.QiushuPankou2),
		"大小热度" + analysisRuleHeatBucket(item.Item.QiuShuTouZhu, "大热", "小热"),
	}
}

func analysisRuleScoreElements(item analysisRuleSnapshotMatch) []string {
	bookmakerShape := analysisRuleScoreShape(item.Bookmaker.Score)
	platformShape := analysisRuleScoreShape(item.Platform.Score)
	return []string{
		"庄家" + item.Bookmaker.Score,
		"平台" + item.Platform.Score,
		analysisRuleAlignedLabel("庄平同比分", "庄平比分分歧", item.Bookmaker.Score, item.Platform.Score, func(value string) string { return value }),
		analysisRuleOptionalText("庄家形态", bookmakerShape),
		analysisRuleOptionalText("平台形态", platformShape),
		analysisRuleAlignedNonEmptyLabel("庄平同形态", bookmakerShape, platformShape),
		"庄家赛果" + analysisRuleOutcomeLabel(item.Bookmaker.Outcome),
		"平台赛果" + analysisRuleOutcomeLabel(item.Platform.Outcome),
		"庄家球数" + item.Bookmaker.Goal,
		"平台球数" + item.Platform.Goal,
		"亚盘" + analysisRuleHandicapBucket(item.Item.YapanPankou2),
		"大小盘口" + analysisRuleGoalLineBucket(item.Item.QiushuPankou2),
	}
}

func analysisRuleAlignedLabel(prefix string, fallback string, left string, right string, labeler func(string) string) string {
	if left == right {
		return prefix + labeler(left)
	}
	return fallback
}

func analysisRuleAlignedNonEmptyLabel(prefix string, left string, right string) string {
	if left != "" && left == right {
		return prefix + left
	}
	return ""
}

func analysisRuleOptionalLabel(prefix string, value string, labeler func(string) string) string {
	if value == "" {
		return ""
	}
	return prefix + labeler(value)
}

func analysisRuleOptionalText(prefix string, value string) string {
	if value == "" {
		return ""
	}
	return prefix + value
}

func analysisRuleScoreShape(score string) string {
	parts := strings.Split(score, ":")
	if len(parts) != 2 {
		return ""
	}
	home := int(parseFloat(parts[0]))
	away := int(parseFloat(parts[1]))
	total := home + away
	totalLabel := "大比分"
	if total <= 1 {
		totalLabel = "低比分"
	} else if total == 2 {
		totalLabel = "2球"
	} else if total == 3 {
		totalLabel = "3球"
	}
	if home == away {
		return "平局" + totalLabel
	}
	outcome := "主胜"
	if home < away {
		outcome = "客胜"
	}
	margin := int(math.Abs(float64(home - away)))
	marginLabel := "大胜"
	if margin == 1 {
		marginLabel = "小胜"
	} else if margin == 2 {
		marginLabel = "中胜"
	}
	return outcome + marginLabel + totalLabel
}

func analysisRuleOutcomeLabel(outcome string) string {
	switch outcome {
	case "home":
		return "主胜"
	case "away":
		return "客胜"
	case "draw":
		return "平局"
	default:
		return "-"
	}
}

func analysisRuleJoin(values []string) string {
	if len(values) == 0 {
		return "-"
	}
	return strings.Join(values, " / ")
}

func analysisRuleProfessionalConsensus(item analysisMatchResponse) string {
	kelly := map[string]bool{}
	for _, value := range item.KaiLiResult {
		if outcome := analysisRuleTextOutcome(value); outcome != "" {
			kelly[outcome] = true
		}
	}
	for _, value := range item.TiCaiResult {
		if outcome := analysisRuleTextOutcome(value); outcome != "" && kelly[outcome] {
			return outcome
		}
	}
	return ""
}

func analysisRuleDrawRiskScore(item analysisMatchResponse, bookmakerOutcome string, platformOutcome string) float64 {
	score := 0.0
	absHandicap := math.Abs(item.YapanPankou2)
	if absHandicap <= 0.25 {
		score += 2
	} else if absHandicap <= 0.5 {
		score += 1
	}
	if math.Abs(item.YapanPankou1)-math.Abs(item.YapanPankou2) >= 0.25 {
		score += 1.5
	}

	sideProbability := math.Max(item.WinProbability, item.LoseProbability)
	if item.DrawProbability > 0 && item.DrawProbability >= sideProbability-10 {
		score += 1.5
	}
	if item.DrawProbability > 0 && item.DrawProbability >= sideProbability-6 {
		score += 1
	}

	if item.QiushuPankou2 > 0 && item.QiushuPankou2 <= 2.5 {
		score += 1
	}
	if bookmakerOutcome != "" && platformOutcome != "" && bookmakerOutcome != platformOutcome && bookmakerOutcome != "draw" && platformOutcome != "draw" {
		score += 1
	}
	professional := analysisRuleProfessionalConsensus(item)
	base := analysisRuleTextOutcome(item.Prediction)
	if professional != "" && base != "" && professional != base {
		score += 1
	}
	if analysisRuleAverageGoalTotal(item.ChangGuiQiuShu) > 0 && analysisRuleAverageGoalTotal(item.ChangGuiQiuShu) <= 2.5 {
		score += 1
	}
	if analysisRuleHistoryOutcome(item) == "draw" {
		score += 1.5
	}
	if analysisRuleHistorySmallScore(item) {
		score += 1
	}
	return score
}

func analysisRuleDrawRiskLabel(score float64, threshold float64, label string) string {
	if score >= threshold {
		return label
	}
	return ""
}

func analysisRuleAverageGoalTotal(value string) float64 {
	parts := strings.FieldsFunc(value, func(r rune) bool { return r == ':' || r == '/' || r == '：' })
	values := []float64{}
	for _, part := range parts {
		number := parseFloat(strings.TrimSpace(part))
		if number > 0 {
			values = append(values, number)
		}
	}
	if len(values) == 0 {
		return 0
	}
	total := 0.0
	for _, value := range values {
		total += value
	}
	return total / float64(len(values))
}

func analysisRuleHistoryOutcome(item analysisMatchResponse) string {
	if len(item.LiangDuiBiSai) < 5 {
		return ""
	}
	homeScore := interfaceToFloat(item.LiangDuiBiSai[3])
	awayScore := interfaceToFloat(item.LiangDuiBiSai[4])
	if homeScore > awayScore {
		return "home"
	}
	if homeScore < awayScore {
		return "away"
	}
	return "draw"
}

func analysisRuleHistorySmallScore(item analysisMatchResponse) bool {
	if len(item.LiangDuiBiSai) < 5 {
		return false
	}
	homeScore := interfaceToFloat(item.LiangDuiBiSai[3])
	awayScore := interfaceToFloat(item.LiangDuiBiSai[4])
	return homeScore+awayScore <= 2
}

func analysisRuleHandicapBucket(value float64) string {
	if math.Abs(value) < 0.25 {
		return "平浅"
	}
	side := "主让"
	if value < 0 {
		side = "客让"
	}
	absValue := math.Abs(value)
	if absValue >= 1 {
		return side + "深"
	}
	if absValue >= 0.5 {
		return side + "中"
	}
	return side + "浅"
}

func analysisRuleGoalLineBucket(value float64) string {
	if value <= 2.25 {
		return "低盘"
	}
	if value >= 2.75 {
		return "高盘"
	}
	return "中盘"
}

func analysisRuleHeatBucket(values []interface{}, leftHot string, rightHot string) string {
	if len(values) < 2 {
		return "-"
	}
	left := interfaceToFloat(values[0])
	right := interfaceToFloat(values[1])
	if left > 65 {
		return leftHot
	}
	if right > 65 {
		return rightHot
	}
	if left-right >= 10 {
		return leftHot
	}
	if right-left >= 10 {
		return rightHot
	}
	return "均衡"
}

func interfaceToFloat(value interface{}) float64 {
	switch typed := value.(type) {
	case float64:
		return typed
	case float32:
		return float64(typed)
	case int:
		return float64(typed)
	case int64:
		return float64(typed)
	case string:
		return parseFloat(typed)
	default:
		return 0
	}
}

func round4(value float64) float64 {
	return math.Round(value*10000) / 10000
}
